//
// Created by roni on 07/10/19.
//

#ifndef KERNEL_PAXOS_PERSISTENCE_READ_PERSISTENCE_DEVICE_OPERATIONS_H
#define KERNEL_PAXOS_PERSISTENCE_READ_PERSISTENCE_DEVICE_OPERATIONS_H

#endif //KERNEL_PAXOS_PERSISTENCE_READ_PERSISTENCE_DEVICE_OPERATIONS_H
